### ISSUE TITLE
Disable video display in pose_camera.py

### ISSUE THREAD

**Issue by Chegde8** [google-coral/project-posenet#12]
Hi,
I need to disable the video output displayed by pose_camera.py.
I am unable to understand where in the code the command to display video on a screen is. Could someone please point me to this?

**Comment by mtyka** [comment]
The video display is part of the gstreamer pipeline. 
Look at gstreamer and see how each pipeline ends in either "waylandsink" or "autovideosink".
If you want a different sink, just replace that with one of the many sinks gstreamer provides.
If you want to completely disable it you can replace it with "fakesink". However in that case I would
suggest removing the entire display branch of the 'tee' and get rid of the overlay code as well, for performance reasons.

**Comment by erdiphd** [comment]
Hello
@mtyka . Could you give more detail how to disable the camera streaming in order to increase the FPS?

Here https://github.com/google-coral/project-posenet/blob/master/gstreamer.py#L349

I replaced `autovideosink` with `fakesink`. I tried to delete some lines as you suggested in the code above. However, I am getting error. Which lines exactly should be deleted ?

Thanks
