### ISSUE TITLE
adjust USB cam frame rate?

### ISSUE THREAD

**Issue by wb666greene** [google-coral/project-posenet#15]
I've a lame webcam:

> 	Index       : 1
	Type        : Video Capture
	Pixel Format: 'YUYV'
	Name        : YUYV 4:2:2
		Size: Discrete 1280x720
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.133s (7.500 fps)
		Size: Discrete 640x480
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.133s (7.500 fps)

How can I adjust the frame rate from 30/1 to 10/1 so I can use 720p?

This is on the Coral dev board.

**Comment by jonasl** [comment]
To change the frame rate, try this change:

```diff
diff --git a/gstreamer.py b/gstreamer.py
index 6cd1bc7..be9a6bf 100644
--- a/gstreamer.py
+++ b/gstreamer.py
@@ -336,7 +336,7 @@ def run_pipeline(inf_callback, render_callback, src_size,
     elif jpeg:
         SRC_CAPS = 'image/jpeg,width={width},height={height},framerate=30/1'
     else:
-        SRC_CAPS = 'video/x-raw,width={width},height={height},framerate=30/1'
+        SRC_CAPS = 'video/x-raw,width={width},height={height},framerate=10/1'
     PIPELINE = 'v4l2src device=%s ! {src_caps}'%videosrc
     if detectCoralDevBoard():
         scale_caps = None
```

Also note that USB webcams typically can't supply raw YUV frames at high rates due to the limited  transfer speed of USB. They typically also support JPEG or h264 streams for higher resolutions. If that's the case for yours, you can run the demo with

python3 pose_camera.py --jpeg
or
python3 pose_camera.py --h264

That may unlock higher resolutions at higher rates for you. See the the other lines setting the variable SRC_CAPS in gstreamer.py for the various cases.

Note that the demo code was recently updated, and now requires the latest version of the Coral Devboard system image and edgetpu APIs.

**Comment by wb666greene** [comment]
@jonasl 
Thanks for the answer.
